apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: fyp-ai-access@direct-topic-422109.iam.gserviceaccount.com
  labels:
    argocd.argoproj.io/instance: auth-api
  name: auth-api
  namespace: fyp
  
  
