
restart-argocd-deployment:
  image: argoproj/argocd
  stage: deploy
  needs: ["Deployment"]
  tags:
    - dind
  needs:
    - job: argocd-deployment
  variables:
    GIT_STRATEGY: none
    ARGOCD_SERVER: "10.0.0.3:31080"
    # below variable come from gitlab global variable, ask gitlab admin
    # ARGOCD_USERNAME: "admin"
    # ARGOCD_PASSWORD: "XXXXXX"
  before_script:
    - ARGOCD_PROJECT_NAME=`echo $ARGOCD_PROJECT_NAME | tr '[:upper:]' '[:lower:]' | sed -e 's/[_]/-/g'`
    - echo "ARGOCD_SERVER:$ARGOCD_SERVER"
    - echo "ARGOCD_PROJECT_NAME:$ARGOCD_PROJECT_NAME"
    - echo "ARGOCD_USERNAME:$ARGOCD_USERNAME"
    
  script:
    - argocd login "${ARGOCD_SERVER}" --insecure --username "${ARGOCD_USERNAME}" --password "${ARGOCD_PASSWORD}" --plaintext
    - argocd app actions run "$ARGOCD_PROJECT_NAME" restart --kind Deployment |& tee response.txt
    # if response.txt exists and has a size greater than zero, exit with error
    - cat response.txt
    - ls -la
    - if [ -s response.txt ]; then exit 1; fi
  only:
    - master
    - dev
