apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{app_name}}"
  namespace: argocd
spec:
  destination:
    namespace: "{{namespace}}"
    server: https://kubernetes.default.svc
  project: "default"
  source:
    path: "{{zone_path}}/{{app_folder_name}}"
    repoURL: "https://192.168.64.188/bes/k8s_deployment.git"
    targetRevision: master
    helm:
      valueFiles:
        - values-dev-common.yaml
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

