replicaCount: 4

config:
  dotnetEnv: "K8S_STG"
  appsettings: |
    {
      "PulsarConsumer": {
        "topic": "persistent://public/default/das_middleware_(idax01_trxn_upload|idax02_evid_upload|imgobj_idax02_evid_upload)(.*_assign_dlq)",
        "PulsarUri": "pulsar://10.14.0.77:6650,10.14.0.78:6650,10.14.0.90:6650",
        "subscription": "DLQConsumer"
      }
    }
